#!/bin/csh
#
#   make a compressed tar file (of the ASCII information only)
#
#   Note that the repository must be called 'gamess' while running this.
#
chdir /u1/mike
set TREE=gamess
#
mv $TREE/object ~/abcxyz-object
mkdir $TREE/object
#
mv $TREE/tests ~/abcxyz-tests
mkdir -p $TREE/tests/standard/scripts
cp -rp ~/abcxyz-tests/standard/* $TREE/tests/standard
#
tar -cvf gamess.tar --exclude .git   --exclude .gitignore \
                    --exclude manual --exclude tinker \
                    --exclude clg   \
                    --exclude '*.x' \
                    --exclude '*.a' \
                    --exclude '*.log' \
                    --exclude $TREE/Makefile \
                    --exclude $TREE/install.info     $TREE
#
rmdir $TREE/object
mv abcxyz-object $TREE/object
#
rm -rf $TREE/tests
mv abcxyz-tests $TREE/tests
#
echo -n "Should I compress the tar file down? (y/n) "
set squeeze=$<
if ($squeeze == y) then
   ls -lF ~mike/gamess.tar
   gzip   ~mike/gamess.tar
   ls -lF ~mike/gamess.tar.gz
else
   ls -lF ~mike/gamess.tar
endif
exit
