#!/bin/csh
set E0=-193.6735869077
set G0=0.014631709

set E=`grep "FINAL U-CAMB3LYP" $1 | tail -1 | awk '{ print $5 }'`0
set G=`grep "RMS GRADIENT" $1 | tail -1 | awk '{ print $4 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr. Gerr=$Gerr. "
exit $ierr
