#!/bin/csh
set E0=-525.4012247423

set E=`grep "FINAL RHF" $1 | tail -1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr. "
exit $ierr
