#!/bin/csh
set E0=-304.8443957505

set E=`grep "FINAL ROHF" $1 | tail -1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr. "
exit $ierr
